Repository TopAcademy2022/resume-creator-backend, pull requests merged in 2025-02, with the labels that each got.

#13 Added Dockerfile. Closed #12
  Dockerfile
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
Labels: enhancement

#15 Added Github action. Closed #14
  .github/workflows/docker-build.yml
  .github/workflows/gradle.yml
Labels: testing

#17 Added build script for core library. Closed #8
  BuildLogicLib.bat
  build.gradle
Labels: enhancement, testing

#20 Added link core for build. Closed #19
  .github/workflows/gradle.yml
  Dockerfile
  README.md
  build-core.bat
  build-core.sh
Labels: enhancement

#21 Added ResumeController. Closed #6
  src/main/java/resume/creator/backend/top/WebConfig.java
  src/main/java/resume/creator/backend/top/controllers/ResumeController.java
  src/main/java/resume/creator/backend/top/models/Answer.java
  src/main/java/resume/creator/backend/top/models/ResumeQuestion.java
  src/main/java/resume/creator/backend/top/models/ResumeType.java
Labels: enhancement
